# This Compose file defines two services: web and redis.

# En yaml (équivalent du json) → indentations sont très importantes
include:
  - infra.yaml
services:
  # docker build . -t myimage
  # docker run -dp 8000:5000 myimage
  web:
    build: .
    ports:
      - "8000:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
